name             'simple-web-new'
#maintainer       'YOUR_COMPANY_NAME'
maintainer       'chef'
#maintainer_email 'YOUR_EMAIL'
maintainer_email 'admin@chef.io'
license          'all_rights'
description      'Installs/Configures simple-web'
long_description 'Installs/Configures simple-web'
version          '0.4.42'

depends 'apt'
depends 'httpd'
depends 'aufs'
depends 'motd'
